services:
  meilisearchOne:
    image: getmeili/meilisearch:v1.41.0
    ports:
      - "7701:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meiliOne:/data.ms
    restart: unless-stopped
      
  meilisearchTwo:
    image: getmeili/meilisearch:v1.42.1
    ports:
      - "7702:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meiliTwo:/data.ms
    restart: unless-stopped

  meilisearchThree:
    image: getmeili/meilisearch:v1.43.0
    ports:
      - "7703:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meiliThree:/data.ms
    restart: unless-stopped

  meilisearchNewest:
    image: getmeili/meilisearch:v1.44.0
    ports:
      - "7704:7700"
    environment:
      - MEILI_MASTER_KEY=masterKey
      - MEILI_NO_ANALYTICS=true
    volumes:
      - meiliLatest:/data.ms
    restart: unless-stopped

volumes:
  meiliOne:
  meiliTwo:
  meiliThree:
  meiliLatest: